import { PrismaClient } from "@prisma/client";
import { seedBase } from "./seed";

const db = new PrismaClient({
  datasources: { db: { url: process.env.DIRECT_DATABASE_URL } },
});

async function main() {
  await seedBase();

  // ---------------------------------------------------------------------------
  // Mock Boutiques (dev only)
  // ---------------------------------------------------------------------------
  const boutiquesData = [
    { slug: "siam-couture",        name: "Siam Couture",             ownerName: "คุณนิด",         areaKey: "Siam",        areaLabel: "Siam · ปทุมวัน",         address: "ชั้น 3, Siam Paragon · BTS สยาม",                  hours: "จันทร์-เสาร์ 11:00-19:00", lineUrl: "https://line.me/R/ti/p/@siamcouture",       instagram: "@siamcouture.bkk",    sinceYear: 2018, coverColor: "rose",   tag: "ชุดราตรีและงานหมั้นโทนหวานคลาสสิก ผ้าซิลค์ ลูกไม้ ออร์แกนซ่า — คัดจากดีไซเนอร์ไทย",     story: "Siam Couture เริ่มจากร้านชุดเจ้าสาวเล็กๆ ในสยามตั้งแต่ปี 2018",           featured: true,  district: "ปทุมวัน",     subdistrict: "ปทุมวัน",     province: "กรุงเทพมหานคร", postalCode: "10330" },
    { slug: "thonglor-atelier",    name: "Thonglor Atelier",         ownerName: "คุณแอน",         areaKey: "Thonglor",    areaLabel: "Thonglor · วัฒนา",        address: "Eight Thonglor (ชั้น 2), ซอย 13 · BTS ทองหล่อ",     hours: "ทุกวัน 12:00-20:00",       lineUrl: "https://line.me/R/ti/p/@thonglor",          instagram: "@thonglor.atelier",   sinceYear: 2020, coverColor: "navy",   tag: "ดีไซน์โมเดิร์น ทรงคม สีสะดุดตา — งานเลี้ยงค่ำ ปาร์ตี้ ค็อกเทล หรือชุดทำงาน statement",  story: "Thonglor Atelier ก่อตั้งปี 2020 คัดดีไซเนอร์ที่มี vision ชัด",            featured: true,  district: "วัฒนา",       subdistrict: "คลองตันเหนือ", province: "กรุงเทพมหานคร", postalCode: "10110" },
    { slug: "ekkamai-edit",        name: "Ekkamai Edit",             ownerName: "คุณเฟิร์น",      areaKey: "Ekkamai",     areaLabel: "Ekkamai · วัฒนา",         address: "Ekkamai 12 · BTS เอกมัย",                           hours: "จันทร์-เสาร์ 12:00-19:00", lineUrl: "https://line.me/R/ti/p/@ekkamai.edit",      instagram: "@ekkamai.edit",       sinceYear: 2021, coverColor: "ivory",  tag: "Modern minimalist — ผ้าโทนกลาง ทรงคอลัมน์สะอาดตา",                         story: "Ekkamai Edit คัดเฉพาะชุดที่ออกแบบมาเรียบง่ายที่สุด",                      featured: true,  district: "วัฒนา",       subdistrict: "พระโขนงเหนือ", province: "กรุงเทพมหานคร", postalCode: "10110" },
    { slug: "phrom-phong-bridal",  name: "Phrom Phong Bridal",       ownerName: "คุณพิม",         areaKey: "Phrom Phong", areaLabel: "Phrom Phong · คลองเตย",   address: "Emporium Tower (ชั้น 3) · BTS พร้อมพงษ์",          hours: "จันทร์-อาทิตย์ 11:00-20:00", lineUrl: "https://line.me/R/ti/p/@phromphongbridal", instagram: "@phromphong.bridal",  sinceYear: 2017, coverColor: "ivory",  tag: "ชุดเจ้าสาวระดับพรีเมียม ผ้านำเข้าจากยุโรป งานปัก hand-made ทุกตัว",        story: "ร้านชุดเจ้าสาวเฉพาะทาง บริการ alteration ครบวงจร",                        featured: true,  district: "วัฒนา",       subdistrict: "คลองตันเหนือ", province: "กรุงเทพมหานคร", postalCode: "10110" },
    { slug: "ari-vintage-closet",  name: "Ari Vintage Closet",       ownerName: "คุณกาย",         areaKey: "Ari",         areaLabel: "Ari · พญาไท",             address: "Ari Soi 4 · BTS อารีย์",                            hours: "พุธ-อาทิตย์ 12:00-20:00",  lineUrl: "https://line.me/R/ti/p/@aricloset",         instagram: "@ari.vintage.closet", sinceYear: 2020, coverColor: "purple", tag: "ชุดวินเทจสไตล์ 70-80s + ชุด re-imagined โดยดีไซเนอร์ไทยรุ่นใหม่",          story: "Ari Vintage Closet สะสมชุดวินเทจจากญี่ปุ่นและยุโรป",                      featured: true,  district: "พญาไท",       subdistrict: "สามเสนใน",     province: "กรุงเทพมหานคร", postalCode: "10400" },
    { slug: "asok-style-co",       name: "Asok Style Co.",           ownerName: "คุณเบลล์",       areaKey: "Asok",        areaLabel: "Asok · คลองเตย",          address: "Terminal 21 (ชั้น 2) · BTS อโศก",                  hours: "ทุกวัน 11:00-21:00",       lineUrl: "https://line.me/R/ti/p/@asokstyle",         instagram: "@asokstyleco",        sinceYear: 2019, coverColor: "navy",   tag: "ชุดทำงานและคอนเฟอเรนซ์ที่ดูเด่น เน้นผ้าและทรง mix-and-match",             story: "Asok Style Co. เกิดจาก consultant ที่อยากใส่ชุดดีในการประชุม",            featured: true,  district: "วัฒนา",       subdistrict: "คลองเตยเหนือ", province: "กรุงเทพมหานคร", postalCode: "10110" },
    { slug: "sathorn-atelier",     name: "Sathorn Atelier",          ownerName: "คุณภา",          areaKey: "Sathorn",     areaLabel: "Sathorn · ยานนาวา",       address: "The Met Sathorn · BTS ช่องนนทรี",                  hours: "จันทร์-เสาร์ 10:30-19:00", lineUrl: "https://line.me/R/ti/p/@sathornatelier",    instagram: "@sathorn.atelier",    sinceYear: 2018, coverColor: "black",  tag: "ชุดราตรีคลาสสิก สไตล์ formal สำหรับ corporate gala",                       story: "Sathorn Atelier เน้นบริการลูกค้า expat และนักธุรกิจ",                     featured: false, district: "สาทร",         subdistrict: "ทุ่งวัดดอน",   province: "กรุงเทพมหานคร", postalCode: "10120" },
    { slug: "silom-eveningwear",   name: "Silom Eveningwear",        ownerName: "คุณนุ้ย",        areaKey: "Silom",       areaLabel: "Silom · บางรัก",          address: "ถนนสีลม ซอย 12 · BTS ศาลาแดง",                    hours: "จันทร์-เสาร์ 11:00-19:30", lineUrl: "https://line.me/R/ti/p/@silomeveningwear",  instagram: "@silom.eveningwear",  sinceYear: 2016, coverColor: "red",    tag: "ชุดสีจัด ทรงเด่น ใส่ไปงานค่ำสำคัญ",                                       story: "ร้านชุดราตรีเก่าแก่ของสีลม",                                              featured: false, district: "บางรัก",       subdistrict: "สีลม",         province: "กรุงเทพมหานคร", postalCode: "10500" },
    { slug: "ploenchit-premier",   name: "Ploenchit Premier",        ownerName: "คุณแคทเธอรีน",  areaKey: "Ploenchit",   areaLabel: "Ploenchit · ปทุมวัน",     address: "Central Embassy (ชั้น 4) · BTS เพลินจิต",          hours: "ทุกวัน 10:00-22:00",       lineUrl: "https://line.me/R/ti/p/@ploenchitpremier",  instagram: "@ploenchit.premier",  sinceYear: 2015, coverColor: "ivory",  tag: "ดีไซเนอร์ระดับนานาชาติ สำหรับ red carpet",                                  story: "Ploenchit Premier นำเข้าและให้เช่าชุดดีไซเนอร์ระดับโลก",                featured: false, district: "ปทุมวัน",     subdistrict: "ลุมพินี",      province: "กรุงเทพมหานคร", postalCode: "10330" },
    { slug: "watthana-bridal",     name: "Watthana Bridal House",    ownerName: "คุณส้ม",         areaKey: "Watthana",    areaLabel: "Watthana · สุขุมวิท",     address: "Sukhumvit 39 · BTS พร้อมพงษ์",                     hours: "นัดล่วงหน้าเท่านั้น",      lineUrl: "https://line.me/R/ti/p/@watthanabridal",    instagram: "@watthana.bridalhouse", sinceYear: 2014, coverColor: "rose",  tag: "ชุดเจ้าสาวสไตล์ Thai-Western fusion",                                      story: "Watthana Bridal House เชี่ยวชาญการผสานชุดไทยประยุกต์กับ silhouette ตะวันตก", featured: false, district: "วัฒนา", subdistrict: "คลองตันเหนือ", province: "กรุงเทพมหานคร", postalCode: "10110" },
    { slug: "the-dress-library",   name: "The Dress Library",        ownerName: "คุณป้อบ",        areaKey: "Thonglor",    areaLabel: "Thonglor · วัฒนา",        address: "Soi Thonglor 25 · BTS ทองหล่อ",                    hours: "จันทร์-อาทิตย์ 11:30-20:00", lineUrl: "https://line.me/R/ti/p/@dresslibrary",   instagram: "@thedresslibrary.bkk", sinceYear: 2022, coverColor: "ivory", tag: "Curated mix ชุดดีไซเนอร์หลายแบรนด์ในร้านเดียว",                            story: "The Dress Library คือ shared closet ของผู้หญิง Bangkok สมัยใหม่",        featured: false, district: "วัฒนา",       subdistrict: "คลองตันเหนือ", province: "กรุงเทพมหานคร", postalCode: "10110" },
    { slug: "chitlom-boutique",    name: "Chitlom Boutique",         ownerName: "คุณกิ๊ฟ",        areaKey: "Chitlom",     areaLabel: "Chitlom · ปทุมวัน",       address: "Central Chidlom (ชั้น 2) · BTS ชิดลม",             hours: "ทุกวัน 10:30-22:00",       lineUrl: "https://line.me/R/ti/p/@chitlomboutique",   instagram: "@chitlom.boutique",   sinceYear: 2019, coverColor: "rose",   tag: "ชุดเช่าราคาเข้าถึงได้ ดีไซน์น่ารัก เหมาะกับสาวออฟฟิศ",                   story: "Chitlom Boutique เน้นกลุ่ม first-jobber",                                 featured: false, district: "ปทุมวัน",     subdistrict: "ลุมพินี",      province: "กรุงเทพมหานคร", postalCode: "10330" },
    { slug: "sukhumvit-11",        name: "Sukhumvit 11 Studio",      ownerName: "คุณมิ้น",        areaKey: "Sukhumvit 11",areaLabel: "Sukhumvit 11 · วัฒนา",    address: "Sukhumvit Soi 11 · BTS นานา",                      hours: "พุธ-อาทิตย์ 14:00-22:00",  lineUrl: "https://line.me/R/ti/p/@suk11studio",       instagram: "@sukhumvit11.studio", sinceYear: 2020, coverColor: "navy",   tag: "ชุดปาร์ตี้และคลับสไตล์ Bangkok night life",                                story: "Sukhumvit 11 Studio ตั้งบนซอย night life",                                featured: false, district: "คลองเตย",     subdistrict: "คลองเตย",      province: "กรุงเทพมหานคร", postalCode: "10110" },
    { slug: "sala-daeng-couture",  name: "Sala Daeng Couture",       ownerName: "คุณนัท",         areaKey: "Sala Daeng",  areaLabel: "Sala Daeng · บางรัก",     address: "ถนนคอนแวนต์ · BTS ศาลาแดง",                       hours: "จันทร์-เสาร์ 10:00-19:00", lineUrl: "https://line.me/R/ti/p/@saladaengcouture",  instagram: "@saladaeng.couture",  sinceYear: 2017, coverColor: "ivory",  tag: "ชุดคลาสสิกตลอดกาล ผ้าซิลค์ตัดเย็บประณีต",                                 story: "Sala Daeng Couture สืบทอดจากร้านชุดเก่าของซอยคอนแวนต์",                  featured: false, district: "บางรัก",       subdistrict: "สีลม",         province: "กรุงเทพมหานคร", postalCode: "10500" },
    { slug: "bangrak-bridal",      name: "Bangrak Bridal Co.",       ownerName: "คุณแหม่ม",       areaKey: "Bangrak",     areaLabel: "Bangrak · บางรัก",        address: "ถนนเจริญกรุง · MRT สามยอด",                       hours: "จันทร์-อาทิตย์ 10:00-19:00", lineUrl: "https://line.me/R/ti/p/@bangrakbridal",  instagram: "@bangrak.bridal",     sinceYear: 2018, coverColor: "rose",   tag: "ชุดเจ้าสาวราคามิตรภาพ ทั้งให้เช่าและตัดใหม่",                             story: "Bangrak Bridal เกิดจากความเชื่อว่าวันแต่งงานไม่ควรกินงบเกินจำเป็น",     featured: false, district: "บางรัก",       subdistrict: "บางรัก",       province: "กรุงเทพมหานคร", postalCode: "10500" },
    { slug: "pra-sai-couture",     name: "Pra Sai Couture",          ownerName: "คุณปราชญ์",      areaKey: "Watthana",    areaLabel: "Sukhumvit 31 · วัฒนา",   address: "Sukhumvit 31 · BTS พร้อมพงษ์",                     hours: "นัดล่วงหน้า",              lineUrl: "https://line.me/R/ti/p/@prasaicouture",     instagram: "@prasai.couture",     sinceYear: 2021, coverColor: "purple", tag: "Thai contemporary — ผสานเทคนิคไทย-สากล",                                   story: "Pra Sai Couture สนับสนุนช่างผ้าไหมไทยและดีไซเนอร์รุ่นใหม่",             featured: false, district: "วัฒนา",       subdistrict: "คลองตันเหนือ", province: "กรุงเทพมหานคร", postalCode: "10110" },
    { slug: "sai-mai",             name: "Sai Mai Designs",          ownerName: "คุณจอย",         areaKey: "Pratunam",    areaLabel: "Pratunam · ราชเทวี",      address: "Platinum Mall · BTS ราชเทวี",                      hours: "ทุกวัน 10:00-20:00",       lineUrl: "https://line.me/R/ti/p/@saimaidesigns",     instagram: "@saimai.designs",     sinceYear: 2020, coverColor: "green",  tag: "ดีไซเนอร์ไทยรุ่นใหม่ ราคา accessible",                                     story: "Sai Mai Designs คัดดีไซเนอร์ไทยใหม่ๆ ทุกเดือน",                          featured: false, district: "ราชเทวี",     subdistrict: "ถนนเพชรบุรี",  province: "กรุงเทพมหานคร", postalCode: "10400" },
    { slug: "bangkok-bridal-studio",name: "Bangkok Bridal Studio",   ownerName: "คุณก้อย",        areaKey: "Sathorn",     areaLabel: "Sathorn · สาทร",          address: "Empire Tower · BTS ช่องนนทรี",                     hours: "นัดล่วงหน้า",              lineUrl: "https://line.me/R/ti/p/@bkkbridal",         instagram: "@bangkok.bridal.studio", sinceYear: 2013, coverColor: "ivory", tag: "Full-service bridal — ชุด เครื่องประดับ veil, shoes ครบ",                  story: "Bangkok Bridal Studio เป็น one-stop bridal ที่เก่าแก่ของกรุงเทพ",       featured: false, district: "สาทร",         subdistrict: "ทุ่งวัดดอน",   province: "กรุงเทพมหานคร", postalCode: "10120" },
    { slug: "closet-collective",   name: "Closet Collective",        ownerName: "คุณนิว",         areaKey: "Ari",         areaLabel: "Ari · พญาไท",             address: "Ari Soi 1 · BTS อารีย์",                            hours: "จันทร์-เสาร์ 11:00-20:00", lineUrl: "https://line.me/R/ti/p/@closetcollective",  instagram: "@closetcollective.bkk", sinceYear: 2023, coverColor: "blue",  tag: "Peer-to-peer dress rental — ชุดจริงจากตู้สาวๆ ในกรุงเทพ",                  story: "Closet Collective เกิดจาก idea ของกลุ่มเพื่อนที่อยากเปลี่ยนตู้เสื้อผ้าให้เป็นรายได้", featured: false, district: "พญาไท", subdistrict: "สามเสนใน", province: "กรุงเทพมหานคร", postalCode: "10400" },
    { slug: "riverside-atelier",   name: "Riverside Atelier",        ownerName: "คุณริน",         areaKey: "Charoenkrung",areaLabel: "Charoenkrung · บางรัก",   address: "ถนนเจริญกรุง 38 · BTS สะพานตากสิน",               hours: "พฤ-อาทิตย์ 12:00-19:00",   lineUrl: "https://line.me/R/ti/p/@riversideatelier",  instagram: "@riverside.atelier",  sinceYear: 2019, coverColor: "blue",   tag: "Destination wedding และงาน outdoor garden",                                 story: "Riverside Atelier ตั้งใกล้แม่น้ำ มี private fitting room",               featured: false, district: "บางรัก",       subdistrict: "บางรัก",       province: "กรุงเทพมหานคร", postalCode: "10500" },
    { slug: "lumpini-lookbook",    name: "Lumpini Lookbook",         ownerName: "คุณมายด์",       areaKey: "Lumpini",     areaLabel: "Lumpini · ปทุมวัน",       address: "ถนนวิทยุ · MRT ลุมพินี",                           hours: "ทุกวัน 11:00-20:00",       lineUrl: "https://line.me/R/ti/p/@lumpinilookbook",   instagram: "@lumpini.lookbook",   sinceYear: 2022, coverColor: "green",  tag: "Sporty chic ใส่ได้ทั้งงานและ casual",                                       story: "Lumpini Lookbook สำหรับสาวที่อยากเปลี่ยนจากชุดงานเป็น cocktail",        featured: false, district: "ปทุมวัน",     subdistrict: "ลุมพินี",      province: "กรุงเทพมหานคร", postalCode: "10330" },
    { slug: "phra-khanong-edit",   name: "Phra Khanong Edit",        ownerName: "คุณอ๊อด",        areaKey: "Phra Khanong",areaLabel: "Phra Khanong · คลองเตย",  address: "W District · BTS พระโขนง",                         hours: "พุธ-อาทิตย์ 13:00-21:00",  lineUrl: "https://line.me/R/ti/p/@phrakhanongedit",   instagram: "@phrakhanong.edit",   sinceYear: 2021, coverColor: "black",  tag: "Alternative styles — เน้นความเป็นตัวเอง",                                   story: "Phra Khanong Edit รับลูกค้าที่เบื่อชุดทั่วไป",                           featured: false, district: "พระโขนง",     subdistrict: "บางจาก",       province: "กรุงเทพมหานคร", postalCode: "10260" },
    { slug: "onnut-atelier",       name: "Onnut Atelier",            ownerName: "คุณบี",          areaKey: "Onnut",       areaLabel: "Onnut · พระโขนง",         address: "Centre One Onnut · BTS อ่อนนุช",                   hours: "จันทร์-อาทิตย์ 10:30-20:00", lineUrl: "https://line.me/R/ti/p/@onnutatelier",    instagram: "@onnut.atelier",      sinceYear: 2020, coverColor: "ivory",  tag: "ชุดราคาเข้าถึงได้ในย่านอ่อนนุช",                                           story: "Onnut Atelier เกิดจากดีไซเนอร์ที่อยากเปิดร้านในย่านชานเมือง",           featured: false, district: "สวนหลวง",     subdistrict: "อ่อนนุช",      province: "กรุงเทพมหานคร", postalCode: "10250" },
    { slug: "yaowarat-heritage",   name: "Yaowarat Heritage",        ownerName: "คุณเล้ง",        areaKey: "Yaowarat",    areaLabel: "Yaowarat · สัมพันธวงศ์",  address: "ถนนเยาวราช · MRT วัดมังกร",                       hours: "จันทร์-อาทิตย์ 10:00-19:00", lineUrl: "https://line.me/R/ti/p/@yaowaratheritage", instagram: "@yaowarat.heritage",  sinceYear: 2012, coverColor: "red",    tag: "ชุดเจ้าสาวจีน-ไทย Tea ceremony, ฉีพ้าว, ม้งกัว",                          story: "Yaowarat Heritage สืบทอดประเพณีชุดจีน-ไทย รุ่น 3 ของครอบครัว",         featured: false, district: "สัมพันธวงศ์", subdistrict: "จักรวรรดิ",    province: "กรุงเทพมหานคร", postalCode: "10100" },
    { slug: "wireless-couture",    name: "Wireless Couture",         ownerName: "คุณเอม",         areaKey: "Wireless",    areaLabel: "Wireless · ปทุมวัน",      address: "All Seasons Place · BTS เพลินจิต",                 hours: "จันทร์-ศุกร์ 10:00-19:00", lineUrl: "https://line.me/R/ti/p/@wirelesscouture",   instagram: "@wireless.couture",   sinceYear: 2016, coverColor: "navy",   tag: "ชุดทางการ classic สำหรับ embassy events",                                   story: "Wireless Couture ตั้งใกล้สถานทูต ลูกค้าหลักคือภรรยานักการทูต",          featured: false, district: "ปทุมวัน",     subdistrict: "ลุมพินี",      province: "กรุงเทพมหานคร", postalCode: "10330" },
    { slug: "soi-49-studio",       name: "Soi 49 Studio",            ownerName: "คุณกุ้ง",        areaKey: "Phrom Phong", areaLabel: "Sukhumvit 49 · พร้อมพงษ์", address: "Sukhumvit Soi 49/12 · BTS พร้อมพงษ์",             hours: "จันทร์-เสาร์ 12:00-20:00", lineUrl: "https://line.me/R/ti/p/@soi49studio",       instagram: "@soi49.studio",       sinceYear: 2021, coverColor: "purple", tag: "Modern Thai designers under one roof",                                       story: "Soi 49 Studio เป็น showroom ของ 5 แบรนด์ดีไซเนอร์ไทยร่วมสมัย",         featured: false, district: "วัฒนา",       subdistrict: "คลองตันเหนือ", province: "กรุงเทพมหานคร", postalCode: "10110" },
    { slug: "surawong-suite",      name: "Surawong Suite",           ownerName: "คุณซู",          areaKey: "Surawong",    areaLabel: "Surawong · บางรัก",       address: "ถนนสุรวงศ์ · BTS ศาลาแดง",                        hours: "จันทร์-เสาร์ 11:00-19:00", lineUrl: "https://line.me/R/ti/p/@surawongsuite",     instagram: "@surawong.suite",     sinceYear: 2018, coverColor: "red",    tag: "Eveningwear specialty — gowns เท่านั้น ราคา premium",                      story: "Surawong Suite รับเฉพาะลูกค้าที่ต้องการ gown สำหรับงานสำคัญ",           featured: false, district: "บางรัก",       subdistrict: "สุริยวงศ์",    province: "กรุงเทพมหานคร", postalCode: "10500" },
    { slug: "sathorn-soiree",      name: "Sathorn Soiree",           ownerName: "คุณป้อ",         areaKey: "Sathorn",     areaLabel: "Sathorn · สาทร",          address: "ถนนสาทรเหนือ · BTS ช่องนนทรี",                    hours: "พุธ-อาทิตย์ 13:00-20:00",  lineUrl: "https://line.me/R/ti/p/@sathornsoiree",     instagram: "@sathorn.soiree",     sinceYear: 2022, coverColor: "purple", tag: "Cocktail party specialist — ชุดสั้น สีเด่น ทรงทันสมัย",                    story: "Sathorn Soiree เน้นกลุ่มลูกค้าที่ต้องไปงาน cocktail หลายๆ งานต่อเดือน", featured: false, district: "สาทร",        subdistrict: "ทุ่งวัดดอน",   province: "กรุงเทพมหานคร", postalCode: "10120" },
    { slug: "sukhumvit-couture",   name: "Sukhumvit Couture",        ownerName: "คุณตา",          areaKey: "Phrom Phong", areaLabel: "EmQuartier · พร้อมพงษ์",  address: "EmQuartier (ชั้น 4) · BTS พร้อมพงษ์",              hours: "ทุกวัน 10:00-22:00",       lineUrl: "https://line.me/R/ti/p/@sukhumvitcouture",  instagram: "@sukhumvit.couture",  sinceYear: 2014, coverColor: "ivory",  tag: "Mainstream luxury — แบรนด์ตปท.นำเข้า",                                     story: "Sukhumvit Couture นำเข้าชุดจาก Milan, Paris, NY",                        featured: false, district: "วัฒนา",       subdistrict: "คลองตันเหนือ", province: "กรุงเทพมหานคร", postalCode: "10110" },
    { slug: "closet-at-park",      name: "The Closet at Park",       ownerName: "คุณมิว",         areaKey: "Lumpini",     areaLabel: "Lumpini Park · ปทุมวัน",  address: "ใกล้ Lumpini Park · MRT ลุมพินี",                  hours: "นัดล่วงหน้าเท่านั้น",      lineUrl: "https://line.me/R/ti/p/@closetatpark",      instagram: "@theclosetatpark",    sinceYear: 2023, coverColor: "rose",   tag: "Community closet — เกิดจากกลุ่มแม่บ้านที่จัดเก็บชุดร่วมกัน",               story: "The Closet at Park เริ่มจากกลุ่มเพื่อน 10 คนที่นำชุดมาเก็บไว้ในที่เดียว", featured: false, district: "ปทุมวัน",    subdistrict: "ลุมพินี",      province: "กรุงเทพมหานคร", postalCode: "10330" },
  ] as const;

  for (const b of boutiquesData) {
    await db.boutique.upsert({
      where: { slug: b.slug },
      update: {},
      create: {
        slug: b.slug, name: b.name, ownerName: b.ownerName,
        areaKey: b.areaKey, areaLabel: b.areaLabel, address: b.address,
        district: b.district, subdistrict: b.subdistrict,
        province: b.province, postalCode: b.postalCode,
        hours: b.hours, lineUrl: b.lineUrl, instagram: b.instagram,
        sinceYear: b.sinceYear, coverColor: b.coverColor,
        tag: b.tag, story: b.story, featured: b.featured,
        status: "live", kycStatus: "none",
      },
    });
  }

  // ---------------------------------------------------------------------------
  // Mock Dresses (dev only)
  // ---------------------------------------------------------------------------
  type BoutiqueRow = { id: string; slug: string; lineUrl: string };
  const boutiques: BoutiqueRow[] = await db.boutique.findMany({ select: { id: true, slug: true, lineUrl: true } });
  const bySlug = new Map<string, BoutiqueRow>(boutiques.map((b) => [b.slug, b]));

  const dressesData = [
    { slug: "rose-silk-midi",           boutique: "siam-couture",          name: "Rose Silk Midi",           designer: "Atelier Bangkok",   size: "S", color: "rose",   price: 1800, deposit: 8000,  desc: "ชุดเดรสผ้าซิลค์สีกุหลาบ ทรง midi คอวี เหมาะกับงานเลี้ยงค่ำ", occasions: ["engagement","evening"],       adsTier: "free",     featured: false, sponsored: false },
    { slug: "ivory-pleated-gown",       boutique: "thonglor-atelier",      name: "Ivory Pleated Gown",       designer: "Praewa Studio",     size: "M", color: "ivory",  price: 2400, deposit: 12000, desc: "ชุดราตรีสีงาช้าง ผ้าพลีทอัดร้อน ทรงยาวพื้น เหมาะกับงานแต่งงาน", occasions: ["wedding","gala"],             adsTier: "free",     featured: false, sponsored: false },
    { slug: "emerald-velvet-cocktail",  boutique: "siam-couture",          name: "Emerald Velvet Cocktail",  designer: "Asava",             size: "S", color: "green",  price: 2000, deposit: 10000, desc: "เดรสผ้ากำมะหยี่สีมรกต ทรงเข้ารูป เหมาะกับงานค็อกเทล",          occasions: ["cocktail","party"],           adsTier: "free",     featured: false, sponsored: false },
    { slug: "noir-silk-slip",           boutique: "thonglor-atelier",      name: "Noir Silk Slip",           designer: "Kloset",            size: "M", color: "black",  price: 1600, deposit: 8000,  desc: "ชุดสลิปเดรสผ้าซิลค์สีดำ สายเดี่ยว ทรงเรียบหรู",               occasions: ["evening","cocktail","party"], adsTier: "free",     featured: false, sponsored: false },
    { slug: "blush-tulle-ball",         boutique: "siam-couture",          name: "Blush Tulle Ball Gown",    designer: "Theatre",           size: "S", color: "rose",   price: 3200, deposit: 15000, desc: "ชุดบอลกาวน์ผ้าทูลล์สีชมพูบลัช กระโปรงพอง",                     occasions: ["engagement","gala"],          adsTier: "featured", featured: true,  sponsored: false },
    { slug: "navy-sequin-mini",         boutique: "thonglor-atelier",      name: "Navy Sequin Mini",         designer: "Disaya",            size: "S", color: "navy",   price: 1900, deposit: 9000,  desc: "เดรสสั้นสีกรมท่า ผ้าปักเลื่อม ใส่ออกงานเลี้ยง",               occasions: ["party","evening"],            adsTier: "free",     featured: false, sponsored: false },
    { slug: "champagne-lace-midi",      boutique: "siam-couture",          name: "Champagne Lace Midi",      designer: "Asava",             size: "M", color: "ivory",  price: 2200, deposit: 11000, desc: "ชุดลูกไม้สีแชมเปญ ทรง midi แขนยาว",                             occasions: ["wedding","engagement"],       adsTier: "free",     featured: false, sponsored: false },
    { slug: "scarlet-satin-column",     boutique: "thonglor-atelier",      name: "Scarlet Satin Column",     designer: "Kloset",            size: "S", color: "red",    price: 2600, deposit: 13000, desc: "ชุดราตรีผ้าซาตินสีแดงสด ทรงคอลัมน์ เปิดหลัง",                  occasions: ["evening","gala"],             adsTier: "boost",    featured: false, sponsored: true  },
    { slug: "powder-blue-tea",          boutique: "siam-couture",          name: "Powder Blue Tea Dress",    designer: "Theatre",           size: "M", color: "blue",   price: 1700, deposit: 8500,  desc: "เดรสสีฟ้าพาวเดอร์ ทรง tea length ผ้าชีฟอง บางเบา",             occasions: ["casual","wedding"],           adsTier: "free",     featured: false, sponsored: false },
    { slug: "onyx-tuxedo-jumpsuit",     boutique: "thonglor-atelier",      name: "Onyx Tuxedo Jumpsuit",     designer: "Disaya",            size: "S", color: "black",  price: 2100, deposit: 10000, desc: "จัมป์สูทสีดำสไตล์ทักซิโด้ ตัดเย็บเข้ารูป",                    occasions: ["work","party"],               adsTier: "free",     featured: false, sponsored: false },
    { slug: "lilac-organza-gown",       boutique: "siam-couture",          name: "Lilac Organza Gown",       designer: "Praewa Studio",     size: "M", color: "purple", price: 2800, deposit: 13000, desc: "ชุดราตรีผ้าออร์แกนซ่าสีม่วงไลแลค ทรงเอ-ไลน์",                  occasions: ["engagement","wedding"],       adsTier: "free",     featured: false, sponsored: false },
    { slug: "sage-linen-suit",          boutique: "thonglor-atelier",      name: "Sage Linen Suit Set",      designer: "Asava",             size: "M", color: "green",  price: 1500, deposit: 7500,  desc: "เซ็ตเสื้อเบลเซอร์กับกระโปรงผ้าลินินสีเสจ ใส่ทำงาน",           occasions: ["work","casual"],              adsTier: "free",     featured: false, sponsored: false },
    { slug: "navy-sequin-mini-2",       boutique: "ekkamai-edit",          name: "Navy Sequin Mini",         designer: "Local Atelier",     size: "M", color: "navy",   price: 2000, deposit: 10000, desc: "Sequin Mini จาก Ekkamai Edit — ทรงทันสมัย",                     occasions: ["party","cocktail"],           adsTier: "free",     featured: false, sponsored: false },
    { slug: "sage-chiffon-tea",         boutique: "ekkamai-edit",          name: "Sage Chiffon Tea Dress",   designer: "Bangkok Designer",  size: "L", color: "green",  price: 1700, deposit: 8500,  desc: "Chiffon Tea Dress จาก Ekkamai Edit",                            occasions: ["casual"],                     adsTier: "free",     featured: false, sponsored: false },
    { slug: "ivory-linen-suit",         boutique: "ekkamai-edit",          name: "Ivory Linen Suit",         designer: "— Curated —",       size: "S", color: "ivory",  price: 1800, deposit: 9000,  desc: "Linen Suit จาก Ekkamai Edit — เรียบ หรู ใส่ทำงาน",             occasions: ["work","casual"],              adsTier: "free",     featured: false, sponsored: false },
    { slug: "ivory-tulle-cocktail",     boutique: "phrom-phong-bridal",    name: "Ivory Tulle Cocktail",     designer: "Bangkok Designer",  size: "S", color: "ivory",  price: 2300, deposit: 11500, desc: "Tulle Cocktail จาก Phrom Phong Bridal",                         occasions: ["cocktail"],                   adsTier: "boost",    featured: false, sponsored: true  },
    { slug: "black-silk-slip",          boutique: "ari-vintage-closet",    name: "Noir Silk Slip",           designer: "— Curated —",       size: "L", color: "black",  price: 2000, deposit: 10000, desc: "Silk Slip จาก Ari Vintage Closet",                              occasions: ["evening","cocktail"],         adsTier: "featured", featured: true,  sponsored: false },
    { slug: "rose-lace-midi",           boutique: "ari-vintage-closet",    name: "Rose Lace Midi",           designer: "— Studio —",        size: "S", color: "rose",   price: 2600, deposit: 13000, desc: "Lace Midi จาก Ari Vintage Closet",                              occasions: ["wedding"],                    adsTier: "free",     featured: false, sponsored: false },
    { slug: "navy-satin-column",        boutique: "asok-style-co",         name: "Navy Satin Column",        designer: "— Studio —",        size: "M", color: "navy",   price: 3000, deposit: 15000, desc: "Satin Column จาก Asok Style Co.",                               occasions: ["gala"],                       adsTier: "free",     featured: false, sponsored: false },
    { slug: "rose-organza-ball-gown",   boutique: "asok-style-co",         name: "Rose Organza Ball Gown",   designer: "Local Atelier",     size: "L", color: "rose",   price: 2800, deposit: 14000, desc: "Organza Ball Gown จาก Asok Style Co.",                          occasions: ["engagement","gala"],          adsTier: "free",     featured: false, sponsored: false },
    { slug: "black-sequin-mini",        boutique: "sathorn-atelier",       name: "Noir Sequin Mini",         designer: "Local Atelier",     size: "S", color: "black",  price: 1800, deposit: 9000,  desc: "Sequin Mini จาก Sathorn Atelier",                               occasions: ["party","cocktail"],           adsTier: "free",     featured: false, sponsored: false },
    { slug: "rose-tulle-cocktail",      boutique: "silom-eveningwear",     name: "Rose Tulle Cocktail",      designer: "Bangkok Designer",  size: "L", color: "rose",   price: 2100, deposit: 10500, desc: "Tulle Cocktail จาก Silom Eveningwear",                          occasions: ["cocktail"],                   adsTier: "free",     featured: false, sponsored: false },
    { slug: "red-crepe-jumpsuit",       boutique: "silom-eveningwear",     name: "Crimson Crepe Jumpsuit",   designer: "— Curated —",       size: "S", color: "red",    price: 1900, deposit: 9500,  desc: "Crepe Jumpsuit จาก Silom Eveningwear",                          occasions: ["work","party"],               adsTier: "free",     featured: false, sponsored: false },
    { slug: "ivory-silk-slip",          boutique: "ploenchit-premier",     name: "Ivory Silk Slip",          designer: "— Curated —",       size: "M", color: "ivory",  price: 1700, deposit: 8500,  desc: "Silk Slip จาก Ploenchit Premier",                               occasions: ["evening","cocktail"],         adsTier: "free",     featured: false, sponsored: false },
    { slug: "rose-lace-midi-2",         boutique: "ploenchit-premier",     name: "Rose Lace Midi",           designer: "— Studio —",        size: "L", color: "rose",   price: 2300, deposit: 11500, desc: "Lace Midi จาก Ploenchit Premier",                               occasions: ["wedding"],                    adsTier: "free",     featured: false, sponsored: false },
    { slug: "navy-velvet-gown",         boutique: "ploenchit-premier",     name: "Navy Velvet Gown",         designer: "Local Atelier",     size: "S", color: "navy",   price: 3100, deposit: 15500, desc: "Velvet Gown จาก Ploenchit Premier",                             occasions: ["gala","evening"],             adsTier: "free",     featured: false, sponsored: false },
    { slug: "red-satin-column",         boutique: "watthana-bridal",       name: "Crimson Satin Column",     designer: "— Studio —",        size: "S", color: "red",    price: 2700, deposit: 13500, desc: "Satin Column จาก Watthana Bridal",                              occasions: ["gala"],                       adsTier: "free",     featured: false, sponsored: false },
    { slug: "navy-sequin-mini-3",       boutique: "the-dress-library",     name: "Navy Sequin Mini",         designer: "Local Atelier",     size: "L", color: "navy",   price: 2200, deposit: 11000, desc: "Sequin Mini จาก The Dress Library",                             occasions: ["party","cocktail"],           adsTier: "boost",    featured: false, sponsored: true  },
    { slug: "sage-chiffon-tea-2",       boutique: "the-dress-library",     name: "Sage Chiffon Tea Dress",   designer: "Bangkok Designer",  size: "S", color: "green",  price: 1900, deposit: 9500,  desc: "Chiffon Tea Dress จาก The Dress Library",                       occasions: ["casual"],                     adsTier: "free",     featured: false, sponsored: false },
    { slug: "rose-tulle-cocktail-2",    boutique: "chitlom-boutique",      name: "Rose Tulle Cocktail",      designer: "Bangkok Designer",  size: "M", color: "rose",   price: 2500, deposit: 12500, desc: "Tulle Cocktail จาก Chitlom Boutique",                           occasions: ["cocktail"],                   adsTier: "free",     featured: false, sponsored: false },
    { slug: "black-crepe-jumpsuit",     boutique: "chitlom-boutique",      name: "Noir Crepe Jumpsuit",      designer: "— Curated —",       size: "L", color: "black",  price: 1700, deposit: 8500,  desc: "Crepe Jumpsuit จาก Chitlom Boutique",                           occasions: ["work","party"],               adsTier: "free",     featured: false, sponsored: false },
    { slug: "lilac-beaded-gown",        boutique: "chitlom-boutique",      name: "Lilac Beaded Gown",        designer: "— Studio —",        size: "S", color: "purple", price: 3100, deposit: 15500, desc: "Beaded Gown จาก Chitlom Boutique",                              occasions: ["gala"],                       adsTier: "free",     featured: false, sponsored: false },
    { slug: "navy-silk-slip",           boutique: "sukhumvit-11",          name: "Navy Silk Slip",           designer: "— Curated —",       size: "S", color: "navy",   price: 1500, deposit: 7500,  desc: "Silk Slip จาก Sukhumvit 11 Studio",                             occasions: ["evening","cocktail"],         adsTier: "free",     featured: false, sponsored: false },
    { slug: "red-satin-column-2",       boutique: "sala-daeng-couture",    name: "Crimson Satin Column",     designer: "— Studio —",        size: "L", color: "red",    price: 2400, deposit: 12000, desc: "Satin Column จาก Sala Daeng Couture",                           occasions: ["gala"],                       adsTier: "featured", featured: true,  sponsored: false },
    { slug: "lilac-organza-ball-gown",  boutique: "sala-daeng-couture",    name: "Lilac Organza Ball Gown",  designer: "Local Atelier",     size: "S", color: "purple", price: 3100, deposit: 15500, desc: "Organza Ball Gown จาก Sala Daeng Couture",                      occasions: ["engagement","gala"],          adsTier: "free",     featured: false, sponsored: false },
    { slug: "navy-sequin-mini-4",       boutique: "bangrak-bridal",        name: "Navy Sequin Mini",         designer: "Local Atelier",     size: "M", color: "navy",   price: 2000, deposit: 10000, desc: "Sequin Mini จาก Bangrak Bridal Co.",                            occasions: ["party","cocktail"],           adsTier: "free",     featured: false, sponsored: false },
    { slug: "lilac-tulle-cocktail",     boutique: "pra-sai-couture",       name: "Lilac Tulle Cocktail",     designer: "Bangkok Designer",  size: "S", color: "purple", price: 2300, deposit: 11500, desc: "Tulle Cocktail จาก Pra Sai Couture",                            occasions: ["cocktail"],                   adsTier: "free",     featured: false, sponsored: false },
    { slug: "black-silk-slip-2",        boutique: "sai-mai",               name: "Noir Silk Slip",           designer: "— Curated —",       size: "L", color: "black",  price: 2000, deposit: 10000, desc: "Silk Slip จาก Sai Mai Designs",                                 occasions: ["evening","cocktail"],         adsTier: "free",     featured: false, sponsored: false },
    { slug: "rose-lace-midi-3",         boutique: "sai-mai",               name: "Rose Lace Midi",           designer: "— Studio —",        size: "S", color: "rose",   price: 2600, deposit: 13000, desc: "Lace Midi จาก Sai Mai Designs",                                 occasions: ["wedding"],                    adsTier: "free",     featured: false, sponsored: false },
    { slug: "red-satin-column-3",       boutique: "bangkok-bridal-studio", name: "Crimson Satin Column",     designer: "— Studio —",        size: "M", color: "red",    price: 3000, deposit: 15000, desc: "Satin Column จาก Bangkok Bridal Studio",                        occasions: ["gala"],                       adsTier: "boost",    featured: false, sponsored: true  },
    { slug: "rose-organza-ball-gown-2", boutique: "bangkok-bridal-studio", name: "Rose Organza Ball Gown",   designer: "Local Atelier",     size: "L", color: "rose",   price: 2800, deposit: 14000, desc: "Organza Ball Gown จาก Bangkok Bridal Studio",                   occasions: ["engagement","gala"],          adsTier: "free",     featured: false, sponsored: false },
    { slug: "navy-sequin-mini-5",       boutique: "closet-collective",     name: "Navy Sequin Mini",         designer: "Local Atelier",     size: "S", color: "navy",   price: 1800, deposit: 9000,  desc: "Sequin Mini จาก Closet Collective",                             occasions: ["party","cocktail"],           adsTier: "free",     featured: false, sponsored: false },
    { slug: "rose-tulle-cocktail-3",    boutique: "riverside-atelier",     name: "Rose Tulle Cocktail",      designer: "Bangkok Designer",  size: "L", color: "rose",   price: 2100, deposit: 10500, desc: "Tulle Cocktail จาก Riverside Atelier",                          occasions: ["cocktail"],                   adsTier: "free",     featured: false, sponsored: false },
    { slug: "black-silk-slip-3",        boutique: "lumpini-lookbook",      name: "Noir Silk Slip",           designer: "— Curated —",       size: "M", color: "black",  price: 1700, deposit: 8500,  desc: "Silk Slip จาก Lumpini Lookbook",                                occasions: ["evening","cocktail"],         adsTier: "free",     featured: false, sponsored: false },
    { slug: "navy-velvet-gown-2",       boutique: "lumpini-lookbook",      name: "Navy Velvet Gown",         designer: "Local Atelier",     size: "S", color: "navy",   price: 3100, deposit: 15500, desc: "Velvet Gown จาก Lumpini Lookbook",                              occasions: ["gala","evening"],             adsTier: "free",     featured: false, sponsored: false },
    { slug: "black-satin-column",       boutique: "phra-khanong-edit",     name: "Noir Satin Column",        designer: "— Studio —",        size: "S", color: "black",  price: 2700, deposit: 13500, desc: "Satin Column จาก Phra Khanong Edit",                            occasions: ["gala"],                       adsTier: "free",     featured: false, sponsored: false },
    { slug: "navy-sequin-mini-6",       boutique: "onnut-atelier",         name: "Navy Sequin Mini",         designer: "Local Atelier",     size: "L", color: "navy",   price: 2200, deposit: 11000, desc: "Sequin Mini จาก Onnut Atelier",                                 occasions: ["party","cocktail"],           adsTier: "featured", featured: true,  sponsored: false },
    { slug: "rose-tulle-cocktail-4",    boutique: "yaowarat-heritage",     name: "Rose Tulle Cocktail",      designer: "Bangkok Designer",  size: "M", color: "rose",   price: 2500, deposit: 12500, desc: "Tulle Cocktail จาก Yaowarat Heritage",                          occasions: ["cocktail"],                   adsTier: "free",     featured: false, sponsored: false },
    { slug: "navy-silk-slip-2",         boutique: "wireless-couture",      name: "Navy Silk Slip",           designer: "— Curated —",       size: "S", color: "navy",   price: 1500, deposit: 7500,  desc: "Silk Slip จาก Wireless Couture",                                occasions: ["evening","cocktail"],         adsTier: "boost",    featured: false, sponsored: true  },
    { slug: "red-satin-column-4",       boutique: "soi-49-studio",         name: "Crimson Satin Column",     designer: "— Studio —",        size: "L", color: "red",    price: 2400, deposit: 12000, desc: "Satin Column จาก Soi 49 Studio",                                occasions: ["gala"],                       adsTier: "free",     featured: false, sponsored: false },
    { slug: "red-sequin-mini",          boutique: "surawong-suite",        name: "Crimson Sequin Mini",      designer: "Local Atelier",     size: "M", color: "red",    price: 2000, deposit: 10000, desc: "Sequin Mini จาก Surawong Suite",                                occasions: ["party","cocktail"],           adsTier: "free",     featured: false, sponsored: false },
    { slug: "lilac-tulle-cocktail-2",   boutique: "sathorn-soiree",        name: "Lilac Tulle Cocktail",     designer: "Bangkok Designer",  size: "S", color: "purple", price: 2300, deposit: 11500, desc: "Tulle Cocktail จาก Sathorn Soiree",                             occasions: ["cocktail"],                   adsTier: "free",     featured: false, sponsored: false },
    { slug: "ivory-silk-slip-2",        boutique: "sukhumvit-couture",     name: "Ivory Silk Slip",          designer: "— Curated —",       size: "L", color: "ivory",  price: 2000, deposit: 10000, desc: "Silk Slip จาก Sukhumvit Couture",                               occasions: ["evening","cocktail"],         adsTier: "free",     featured: false, sponsored: false },
    { slug: "red-satin-column-5",       boutique: "closet-at-park",        name: "Crimson Satin Column",     designer: "— Studio —",        size: "M", color: "red",    price: 3000, deposit: 15000, desc: "Satin Column จาก The Closet at Park",                           occasions: ["gala"],                       adsTier: "free",     featured: false, sponsored: false },
    { slug: "rose-organza-ball-gown-3", boutique: "closet-at-park",        name: "Rose Organza Ball Gown",   designer: "Local Atelier",     size: "L", color: "rose",   price: 2800, deposit: 14000, desc: "Organza Ball Gown จาก The Closet at Park",                      occasions: ["engagement","gala"],          adsTier: "free",     featured: false, sponsored: false },
  ];

  let tagSeq = 1;
  for (const d of dressesData) {
    const b = bySlug.get(d.boutique);
    if (!b) { console.warn(`boutique not found: ${d.boutique}`); continue; }
    const tagCode = `DR${String(tagSeq++).padStart(4, "0")}`;
    await db.dress.upsert({
      where: { slug: d.slug },
      update: {},
      create: {
        slug: d.slug, tagCode,
        name: d.name, designer: d.designer,
        boutiqueId: b.id, boutiqueName: bySlug.get(d.boutique)!.slug.split("-").map(w => w[0].toUpperCase() + w.slice(1)).join(" "),
        size: d.size as "XS"|"S"|"M"|"L"|"XL",
        color: d.color as "rose"|"ivory"|"green"|"black"|"navy"|"red"|"blue"|"purple",
        pricePerDay: d.price, deposit: d.deposit,
        description: d.desc, occasions: d.occasions,
        lineUrl: b.lineUrl,
        adsTier: d.adsTier as "free"|"boost"|"featured",
        featured: d.featured, sponsored: d.sponsored,
        status: "live", available: true,
      },
    });
  }

  console.log("✅ Dev seed complete (base + mock boutiques + dresses)");
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => db.$disconnect());
