/**
 * gen-comments.ts — generate COMMENT ON TABLE/COLUMN statements from the
 * `///` doc comments in prisma/schema.prisma (see product/db-restructure/DESIGN.md §9).
 *
 * Usage: npx tsx scripts/gen-comments.ts > /tmp/comments.sql
 * The output is pasted (once) into the restructure_v1 migration so SQL comments
 * and Prisma doc comments never drift. Future migrations must add their own
 * COMMENT ON lines for new tables/columns.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";

const schema = readFileSync(join(__dirname, "..", "prisma", "schema.prisma"), "utf8");
const lines = schema.split("\n");

// Pass 1: collect model + enum names (to tell relation fields from real columns).
const modelNames = new Set<string>();
const enumNames = new Set<string>();
for (const line of lines) {
  const m = line.match(/^model\s+(\w+)\s*\{/);
  if (m) modelNames.add(m[1]);
  const e = line.match(/^enum\s+(\w+)\s*\{/);
  if (e) enumNames.add(e[1]);
}

const esc = (s: string) => s.replace(/'/g, "''");

// Canonical texts for the standard audit columns (DESIGN.md §4) — used when a
// model doesn't repeat the /// doc on them (they are identical on every table).
const AUDIT_DEFAULTS: Record<string, string> = {
  createdBy: "uuid ผู้สร้าง record (NULL = system/seed; ไม่มี FK — ต้องอยู่รอดแม้ user ถูก hard delete)",
  createdAt: "เวลาสร้าง record",
  updatedBy: "uuid ผู้แก้ไขล่าสุด (ไม่มี FK)",
  updatedAt: "เวลาแก้ไขล่าสุด (DB trigger set_updated_at + Prisma @updatedAt)",
};
const out: string[] = [];

// Pass 2: walk models, attach pending /// comments to the next model/field.
let pending: string[] = [];
let inModel = false;
let tableName = "";
let modelName = "";
let tableComment: string[] = [];
let missing: string[] = [];
let columnSql: string[] = [];

function flushModel() {
  if (!inModel) return;
  if (tableComment.length === 0) missing.push(`TABLE ${modelName}`);
  out.push(`COMMENT ON TABLE "${tableName}" IS '${esc(tableComment.join(" "))}';`);
  out.push(...columnSql, "");
  inModel = false;
  columnSql = [];
}

for (const raw of lines) {
  const line = raw.trim();

  const doc = line.match(/^\/\/\/\s?(.*)$/);
  if (doc) { pending.push(doc[1].trim()); continue; }

  const modelStart = line.match(/^model\s+(\w+)\s*\{/);
  if (modelStart) {
    inModel = true;
    modelName = modelStart[1];
    tableName = modelName; // overridden by @@map below
    tableComment = pending;
    pending = [];
    continue;
  }

  if (!inModel) { pending = []; continue; }

  if (line === "}") { flushModel(); pending = []; continue; }

  const mapTable = line.match(/^@@map\("([^"]+)"\)/);
  if (mapTable) {
    tableName = mapTable[1];
    // patch table name into already-emitted column SQL for this model
    columnSql = columnSql.map((s) => s.replace(/^COMMENT ON COLUMN "[^"]+"\./, `COMMENT ON COLUMN "${tableName}".`));
    continue;
  }

  // skip blanks, // comments, other block attributes
  if (line === "" || line.startsWith("//") || line.startsWith("@@")) { pending = []; continue; }

  // field line: <name> <type> [attributes...]
  const field = line.match(/^(\w+)\s+([\w."()\[\]?]+)(\s+.*)?$/);
  if (!field) { pending = []; continue; }
  const [, fieldName, rawType, attrs = ""] = field;
  const baseType = rawType.replace(/[?\[\]]/g, "").replace(/^Unsupported\(.*\)$/, "Unsupported");

  // relation fields (point at another model) are not DB columns
  if (modelNames.has(baseType)) { pending = []; continue; }

  const colMap = attrs.match(/@map\("([^"]+)"\)/);
  const colName = colMap ? colMap[1] : fieldName;
  let text = pending.join(" ");
  if (text === "" && AUDIT_DEFAULTS[fieldName]) text = AUDIT_DEFAULTS[fieldName];
  if (text === "") missing.push(`COLUMN ${modelName}.${fieldName}`);
  columnSql.push(`COMMENT ON COLUMN "${tableName}"."${colName}" IS '${esc(text)}';`);
  pending = [];
}
flushModel();

if (missing.length > 0) {
  console.error("MISSING /// doc comments for:\n  " + missing.join("\n  "));
  process.exit(1);
}
console.log("-- ── COMMENT ON TABLE/COLUMN (generated by scripts/gen-comments.ts from schema.prisma /// docs) ──");
console.log(out.join("\n"));
